"""Add activity/session/stats/admin notifications tables with monthly partitions.

Revision ID: 20260317_0001
Revises:
Create Date: 2026-03-17 22:10:00
"""

from __future__ import annotations

from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20260317_0001"
down_revision = None
branch_labels = None
depends_on = None


def _inspector():
    return sa.inspect(op.get_bind())


def _has_table(table_name: str) -> bool:
    return _inspector().has_table(table_name)


def _has_index(table_name: str, index_name: str) -> bool:
    indexes = _inspector().get_indexes(table_name)
    return any(idx.get("name") == index_name for idx in indexes)


def _create_user_activities_partitioned_pg() -> None:
    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS user_activities (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                user_id INTEGER NOT NULL,
                action VARCHAR(100) NOT NULL,
                details JSONB,
                session_id VARCHAR(50),
                ip_address VARCHAR(45),
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
            ) PARTITION BY RANGE (created_at)
            """
        )
    )

    if not _has_index("user_activities", "ix_user_activities_user_created"):
        op.execute(
            sa.text(
                "CREATE INDEX ix_user_activities_user_created ON user_activities (user_id, created_at)"
            )
        )

    if not _has_index("user_activities", "ix_user_activities_action_created"):
        op.execute(
            sa.text(
                "CREATE INDEX ix_user_activities_action_created ON user_activities (action, created_at)"
            )
        )

    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS user_activities_default
            PARTITION OF user_activities DEFAULT
            """
        )
    )

    now = datetime.utcnow()
    month_start = datetime(now.year, now.month, 1)

    for offset in (-1, 0, 1, 2):
        year = month_start.year
        month = month_start.month + offset
        while month > 12:
            month -= 12
            year += 1
        while month < 1:
            month += 12
            year -= 1

        start = datetime(year, month, 1)
        if month == 12:
            end = datetime(year + 1, 1, 1)
        else:
            end = datetime(year, month + 1, 1)

        partition_name = f"user_activities_{start.strftime('%Y_%m')}"
        op.execute(
            sa.text(
                f"""
                CREATE TABLE IF NOT EXISTS {partition_name}
                PARTITION OF user_activities
                FOR VALUES FROM ('{start.strftime('%Y-%m-%d %H:%M:%S')}')
                         TO ('{end.strftime('%Y-%m-%d %H:%M:%S')}')
                """
            )
        )


def _create_user_activities_standard() -> None:
    if _has_table("user_activities"):
        return

    op.create_table(
        "user_activities",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("session_id", sa.String(length=50), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_user_activities_user_created", "user_activities", ["user_id", "created_at"])
    op.create_index("ix_user_activities_action_created", "user_activities", ["action", "created_at"])


def upgrade() -> None:
    dialect = op.get_bind().dialect.name

    if dialect == "postgresql":
        _create_user_activities_partitioned_pg()
    else:
        _create_user_activities_standard()

    if not _has_table("user_sessions"):
        op.create_table(
            "user_sessions",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False, index=True),
            sa.Column("session_id", sa.String(length=50), nullable=False, unique=True),
            sa.Column("started_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
            sa.Column("last_active", sa.DateTime(), nullable=False, server_default=sa.func.now()),
            sa.Column("ended_at", sa.DateTime(), nullable=True),
            sa.Column("actions_count", sa.Integer(), nullable=False, server_default="0"),
        )

    if not _has_table("user_stats"):
        op.create_table(
            "user_stats",
            sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), primary_key=True),
            sa.Column("total_actions", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("products_added", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("products_deleted", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("alerts_received", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("deals_viewed", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("deals_clicked", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("store_requests_sent", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("categories_added", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("reports_viewed", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("last_active", sa.DateTime(), nullable=True),
            sa.Column("streak_days", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("daily_activity", sa.JSON(), nullable=True),
        )

    if not _has_table("admin_notifications"):
        op.create_table(
            "admin_notifications",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("type", sa.String(length=50), nullable=False),
            sa.Column("title", sa.String(length=200), nullable=False),
            sa.Column("message", sa.Text(), nullable=False),
            sa.Column("icon", sa.String(length=10), nullable=False, server_default="🔔"),
            sa.Column("color", sa.String(length=20), nullable=False, server_default="blue"),
            sa.Column("read", sa.Boolean(), nullable=False, server_default=sa.false()),
            sa.Column("action_url", sa.String(length=200), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        )
        op.create_index("ix_admin_notifications_type", "admin_notifications", ["type"])
        op.create_index("ix_admin_notifications_read", "admin_notifications", ["read"])
        op.create_index("ix_admin_notifications_created_at", "admin_notifications", ["created_at"])


def downgrade() -> None:
    if _has_table("admin_notifications"):
        op.drop_table("admin_notifications")

    if _has_table("user_stats"):
        op.drop_table("user_stats")

    if _has_table("user_sessions"):
        op.drop_table("user_sessions")

    if _has_table("user_activities"):
        op.drop_table("user_activities")
